import{Decimal}from'decimal.js';import{randomUUID}from'node:crypto';
export type LedgerDirection='DEBIT'|'CREDIT';
export type FinancialStatus='PENDING'|'UNDER_REVIEW'|'APPROVED'|'REJECTED'|'CANCELLED'|'PROCESSING'|'COMPLETED';
export interface LedgerEntry{readonly id:string;readonly transactionId:string;readonly walletId:string;readonly asset:'USDT';readonly network:'TRON';readonly direction:LedgerDirection;readonly amount:string;readonly balanceAfter:string;readonly createdAt:string}
export interface DepositRequest{readonly id:string;userId:string;walletId:string;amount:string;txid?:string;status:FinancialStatus;idempotencyKey:string;createdAt:string;reviewedBy?:string;reviewNote?:string;ledgerTransactionId?:string}
export interface AuditEvent{readonly id:string;actorId:string;action:string;targetType:string;targetId:string;before:unknown;after:unknown;createdAt:string;metadata:Record<string,unknown>}
const amount=(value:string)=>{const d=new Decimal(value);if(!d.isFinite()||d.lte(0)||d.decimalPlaces()>6)throw new Error('INVALID_AMOUNT');return d};
/** Demo repository. Production adapter must use PostgreSQL SERIALIZABLE + SELECT FOR UPDATE. */
export class FinancialLedger{
 private balances=new Map<string,Decimal>();private entries:LedgerEntry[]=[];private deposits=new Map<string,DepositRequest>();private idempotency=new Map<string,string>();private audits:AuditEvent[]=[];
 balance(walletId:string){return(this.balances.get(walletId)||new Decimal(0)).toFixed(6)}
 createDeposit(input:{userId:string;walletId:string;amount:string;txid?:string;idempotencyKey:string}){amount(input.amount);const old=this.idempotency.get(input.idempotencyKey);if(old)return this.deposits.get(old)!;const dep:DepositRequest={id:randomUUID(),...input,status:'PENDING',createdAt:new Date().toISOString()};this.deposits.set(dep.id,dep);this.idempotency.set(input.idempotencyKey,dep.id);return dep}
 approveDeposit(id:string,actorId:string,note=''){const dep=this.deposits.get(id);if(!dep)throw new Error('DEPOSIT_NOT_FOUND');if(dep.status==='APPROVED')return dep;if(dep.status!=='PENDING'&&dep.status!=='UNDER_REVIEW')throw new Error('INVALID_STATUS_TRANSITION');const before={...dep},value=amount(dep.amount),transactionId=randomUUID(),next=(this.balances.get(dep.walletId)||new Decimal(0)).plus(value);const entry:LedgerEntry={id:randomUUID(),transactionId,walletId:dep.walletId,asset:'USDT',network:'TRON',direction:'CREDIT',amount:value.toFixed(6),balanceAfter:next.toFixed(6),createdAt:new Date().toISOString()};this.entries.push(entry);this.balances.set(dep.walletId,next);dep.status='APPROVED';dep.reviewedBy=actorId;dep.reviewNote=note;dep.ledgerTransactionId=transactionId;this.audits.push({id:randomUUID(),actorId,action:'DEPOSIT_APPROVED',targetType:'deposit',targetId:id,before,after:{...dep},createdAt:new Date().toISOString(),metadata:{transactionId,asset:'USDT',network:'TRON'}});return dep}
 rejectDeposit(id:string,actorId:string,note:string){const dep=this.deposits.get(id);if(!dep)throw new Error('DEPOSIT_NOT_FOUND');if(!['PENDING','UNDER_REVIEW'].includes(dep.status))throw new Error('INVALID_STATUS_TRANSITION');const before={...dep};dep.status='REJECTED';dep.reviewedBy=actorId;dep.reviewNote=note;this.audits.push({id:randomUUID(),actorId,action:'DEPOSIT_REJECTED',targetType:'deposit',targetId:id,before,after:{...dep},createdAt:new Date().toISOString(),metadata:{}});return dep}
 listDeposits(){return[...this.deposits.values()]};ledgerEntries(){return[...this.entries]};auditEvents(){return[...this.audits]}
}
export const financialLedger=new FinancialLedger();
