import 'dotenv/config';
import express from 'express';import helmet from 'helmet';import cors from 'cors';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import {z,ZodError} from 'zod';import {randomUUID} from 'crypto';
const app=express();const PORT=Number(process.env.PORT||4000);const demo=process.env.DEMO_MODE!=='false';
app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:process.env.APP_ORIGIN||'http://localhost:5173',credentials:true}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use('/api/auth',rateLimit({windowMs:15*60_000,limit:30,standardHeaders:true,legacyHeaders:false}));
type User={id:string,email:string,password:string,role:string,kycStatus:string};const users:User[]=[];const audit:any[]=[];
const secret=process.env.JWT_ACCESS_SECRET||'development-only-secret-change-in-production';
function log(action:string,userId?:string,meta:any={}){audit.push({id:randomUUID(),action,userId:userId||null,timestamp:new Date().toISOString(),...meta})}
function auth(req:any,res:any,next:any){const token=req.cookies.access_token||req.headers.authorization?.replace('Bearer ','');try{req.user=jwt.verify(token,secret);next()}catch{return res.status(401).json({error:{code:'UNAUTHORIZED',message:'Authentication required'}})}}
app.get('/api/health',(_,res)=>res.json({status:'ok',mode:demo?'DEMO':'PRODUCTION',providers:{marketData:process.env.MARKET_DATA_PROVIDER||'NOT_CONFIGURED',payment:process.env.PAYMENT_PROVIDER||'NOT_CONFIGURED'}}));
app.post('/api/auth/register',async(req,res,next)=>{try{const body=z.object({email:z.string().email(),password:z.string().min(12).max(128)}).parse(req.body);if(users.some(u=>u.email===body.email))return res.status(409).json({error:{code:'EMAIL_EXISTS',message:'Email already registered'}});const user={id:randomUUID(),email:body.email,password:await bcrypt.hash(body.password,12),role:'USER',kycStatus:'PENDING'};users.push(user);log('REGISTER',user.id);res.status(201).json({data:{id:user.id,email:user.email,kycStatus:user.kycStatus},meta:{mode:demo?'DEMO':'PRODUCTION'}})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const body=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const user=users.find(u=>u.email===body.email);if(!user||!await bcrypt.compare(body.password,user.password)){log('LOGIN_FAILED',user?.id);return res.status(401).json({error:{code:'INVALID_CREDENTIALS',message:'Invalid credentials'}})}const token=jwt.sign({sub:user.id,role:user.role},secret,{expiresIn:'15m'});res.cookie('access_token',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:900000});log('LOGIN',user.id);res.json({data:{id:user.id,email:user.email,role:user.role},meta:{mode:demo?'DEMO':'PRODUCTION'}})}catch(e){next(e)}});
app.get('/api/wallets',auth,(req:any,res)=>res.json({data:[{id:'demo-wallet',ownerId:req.user.sub,balances:['USD','EUR','USDT','BTC','ETH'].map(asset=>({asset,total:'0',available:'0',locked:'0'}))}],meta:{mode:demo?'DEMO':'PRODUCTION',currencyPrecision:'DECIMAL'}}));
app.get('/api/markets',(_,res)=>res.json({data:[],meta:{mode:demo?'DEMO':'PRODUCTION',provider:process.env.MARKET_DATA_PROVIDER||'NOT_CONFIGURED',message:'No unverified market prices are returned'}}));
app.get('/api/transactions',auth,(_,res)=>res.json({data:[],meta:{mode:demo?'DEMO':'PRODUCTION'}}));
app.get('/api/orders',auth,(_,res)=>res.json({data:[],meta:{mode:demo?'DEMO':'PRODUCTION'}}));
app.post('/api/orders',auth,(req,res)=>res.status(503).json({error:{code:'TRADING_NOT_CONFIGURED',message:'Order execution engine is NOT_CONFIGURED'},meta:{mode:demo?'DEMO':'PRODUCTION'}}));
app.get('/api/investments',auth,(_,res)=>res.json({data:[],meta:{mode:demo?'DEMO':'PRODUCTION',returns:'SIMULATED'}}));
app.post('/api/deposits',auth,(_,res)=>res.status(503).json({error:{code:'PAYMENT_PROVIDER_NOT_CONFIGURED',message:'Deposit provider is NOT_CONFIGURED'}}));
app.post('/api/withdrawals',auth,(_,res)=>res.status(503).json({error:{code:'PAYMENT_PROVIDER_NOT_CONFIGURED',message:'Withdrawal provider is NOT_CONFIGURED'}}));
app.get('/api/audit',auth,(req:any,res)=>{if(req.user.role!=='ADMIN')return res.status(403).json({error:{code:'FORBIDDEN',message:'Admin role required'}});res.json({data:audit})});
app.use((err:any,_req:any,res:any,_next:any)=>{if(err instanceof ZodError)return res.status(422).json({error:{code:'VALIDATION_ERROR',message:'Invalid request',details:err.flatten()}});console.error(err);res.status(500).json({error:{code:'INTERNAL_ERROR',message:'Unexpected server error'}})});
if(process.env.NODE_ENV!=='test')app.listen(PORT,'0.0.0.0',()=>console.log(`Aeta API listening on ${PORT} (${demo?'DEMO':'PRODUCTION'})`));export default app;